config/routes.rb
CarrierwaveJqueryFileUpload::Application.routes.draw do
  resources :pictures
  root :to => 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  validates_presence_of :title, :description, :file
  mount_uploader :file, ImageUploader
  
  #one convenient method to pass jq_upload the necessary information
  def to_jq_upload
  {
    "id" => read_attribute(:id),
    "title" => read_attribute(:title),
    "description" => read_attribute(:description),
    "name" => read_attribute(:file),
    "size" => file.size,
    "url" => file.url,
    "thumbnail_url" => file.thumb.url,
    "delete_url" => picture_path(:id => id),
    "delete_type" => "DELETE" 
   }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @pictures.collect { |p| p.to_jq_upload }.to_json }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
       format.json { render :json => [ @picture.to_jq_upload ].to_json }
      else
        format.json { render :json => [ @picture.to_jq_upload.merge({ :error => "custom_failure" }) ].to_json }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { render :json => true }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "jQuery-File-Upload" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/base/jquery-ui.css", :id => "theme" %>
  <%= javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js" %>
<% end %>

<div id="fileupload">
  <%= form_for @picture, :html => { :multipart => true } do |f| %>
      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>
      <br />
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_field :description %>
      </div>
      <br />
      <div class="fileupload-buttonbar">
          <label class="fileinput-button">
              <span>Add files...</span>
                <%= f.file_field :file %>
          </label>
          <button type="submit" class="start">Start upload</button>
          <button type="reset" class="cancel">Cancel upload</button>
          <button type="button" class="delete">Delete files</button>
      </div>
  <% end %>
  <div class="fileupload-content">
      <table class="files"></table>
      <div class="fileupload-progressbar"></div>
  </div>
</div>

<%= render :partial => "template-upload" %>
<%= render :partial => "template-download" %>

app/views/pictures/_template-download.html.erb
<script id="template-download" type="text/x-jquery-tmpl">
  <tr class="template-download{{if error}} ui-state-error{{/if}}">
      {{if error}}
          <td></td>
          <td class="name">${name}</td>
          <td class="size">${sizef}</td>
          <td class="error" colspan="2">Error:
              {{if error === 1}}File exceeds upload_max_filesize (php.ini directive)
              {{else error === 2}}File exceeds MAX_FILE_SIZE (HTML form directive)
              {{else error === 3}}File was only partially uploaded
              {{else error === 4}}No File was uploaded
              {{else error === 5}}Missing a temporary folder
              {{else error === 6}}Failed to write file to disk
              {{else error === 7}}File upload stopped by extension
              {{else error === 'maxFileSize'}}File is too big
              {{else error === 'minFileSize'}}File is too small
              {{else error === 'acceptFileTypes'}}Filetype not allowed
              {{else error === 'maxNumberOfFiles'}}Max number of files exceeded
              {{else error === 'uploadedBytes'}}Uploaded bytes exceed file size
              {{else error === 'emptyResult'}}Empty file upload result
              {{else}}${error}
              {{/if}}
          </td>
      {{else}}
          <td class="preview">
              {{if thumbnail_url}}
                  <a href="${url}" target="_blank" rel="shadowbox[gallery]" title="${title}"><img src="${thumbnail_url}"></a>
              {{/if}}
          </td>
          <td class="name">
              <a href="${url}"{{if thumbnail_url}} target="_blank"{{/if}} rel="shadowbox" title="${title}">${name}</a>
          </td>
          <td class="size">${sizef}</td>
          <td colspan="2"></td>
          <td><span class="best_in_place" id="best_in_place_picture_title" data-url="/pictures/${id}" data-object="picture" data-attribute="title" data-type="input"> ${title}</span></td>
          <td><span class="best_in_place" id="best_in_place_picture_description" data-url="/pictures/${id}" data-object="picture" data-attribute="description" data-type="input"> ${description}</span></td>
      {{/if}}
      <td class="delete">
          <button data-type="${delete_type}" data-url="${delete_url}">Delete</button>
      </td>
  </tr>
</script>

app/views/pictures/_template-upload.html.erb
<script id="template-upload" type="text/x-jquery-tmpl">
  <tr class="template-upload{{if error}} ui-state-error{{/if}}">
      <td class="preview"></td>
      <td class="name">${name}</td>
      <td class="size">${sizef}</td>
      {{if error}}
          <td class="error" colspan="2">Error:
              {{if error === 'maxFileSize'}}File is too big
              {{else error === 'minFileSize'}}File is too small
              {{else error === 'acceptFileTypes'}}Filetype not allowed
              {{else error === 'maxNumberOfFiles'}}Max number of files exceeded
              {{else}}${error}
              {{/if}}
          </td>
      {{else}}
          <td class="progress"><div></div></td>
          <td class="start"><button>Start</button></td>
      {{/if}}
      <td class="cancel"><button>Cancel</button></td>
  </tr>
</script>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>File</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.title %></td>
    <td><%= picture.description %></td>
    <td><%= image_tag(picture.file_url(:thumb)) if picture.file.present? %></td>
    <td><%= link_to 'Show', picture %></td>
    <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
    <td><%= link_to 'Destroy', picture, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @picture.title %>
</p>

<p>
  <b>Description:</b>
  <%= @picture.description %>
</p>

<p>
  <b>File:</b>
  <%= image_tag(@picture.file_url(:medium)) %>
</p>


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>